### ISSUE TITLE
knife-joyent may be broken when testing with self-signed certs and SDC

### ISSUE THREAD

**Issue by bixu** [joyent/knife-joyent#85]
```
irvin › env | grep JOY
JOYENT_KEYNAME=irvin
JOYENT_USERNAME=yetu
JOYENT_API_URL=https://10.63.8.26

irvin › knife joyent key list -VV
/Users/irvin/.chefdk/gem/ruby/2.1.0/gems/knife-joyent-0.4.10/lib/chef/knife/joyent_base.rb:86:in `output_error': undefined method `response' for #<Excon::Errors::SocketError:0x007fcf4ac257b0> (NoMethodError)
	from /Users/irvin/.chefdk/gem/ruby/2.1.0/gems/knife-joyent-0.4.10/lib/chef/knife/joyent_key_list.rb:24:in `rescue in run'
	from /Users/irvin/.chefdk/gem/ruby/2.1.0/gems/knife-joyent-0.4.10/lib/chef/knife/joyent_key_list.rb:12:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:33:in `load'
	from /opt/chefdk/bin/knife:33:in `<main>'
```

**Comment by kevinykchan** [comment]
Looks like we're seeing a SocketError here, are you sure the host was reachable when you preformed this command?

**Comment by bixu** [comment]
remote host seems to be responding:

```
irvin › env | grep JOY
JOYENT_KEYNAME=irvin
JOYENT_USERNAME=yetu
JOYENT_API_URL=https://eu-ams-1.api.joyentcloud.com
~ @bixu
irvin › export JOYENT_API_URL=https://10.63.8.26
~ @bixu
irvin › knife joyent key list -VV
/Users/irvin/.chefdk/gem/ruby/2.1.0/gems/knife-joyent-0.4.10/lib/chef/knife/joyent_base.rb:86:in `output_error': undefined method `response' for #<Excon::Errors::SocketError:0x007fe22104bd60> (NoMethodError)
	from /Users/irvin/.chefdk/gem/ruby/2.1.0/gems/knife-joyent-0.4.10/lib/chef/knife/joyent_key_list.rb:24:in `rescue in run'
	from /Users/irvin/.chefdk/gem/ruby/2.1.0/gems/knife-joyent-0.4.10/lib/chef/knife/joyent_key_list.rb:12:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:33:in `load'
	from /opt/chefdk/bin/knife:33:in `<main>'
~ @bixu
irvin › telnet 10.63.8.26 443
Trying 10.63.8.26...
Connected to cloudapi.eu-nue-1.yetu.me.
Escape character is '^]'.
^]
```

**Comment by bixu** [comment]
(Note that the hostname for the cloudapi endpoint has been set only in my /etc/hosts file)

**Comment by kevinykchan** [comment]
is the certificate used self-signed?

**Comment by kevinykchan** [comment]
please make sure ```joyent_verify_peer``` is set to ```false``` in your config to skip ssl hostname verification. It is required if you are using self signed certs

**Comment by bixu** [comment]
It's the default SDC cert, so yes.  I'll try this setting (assuming this in knife.rb?)

**Comment by bixu** [comment]
Yes, this does indeed work.  So now I just need to install some real certs :)

**Comment by kevinykchan** [comment]
👍👍👍👍
